# This is an incomplete bundle fragment. Do not attempt to deploy.
applications:
  "docker":
    charm: docker
    annotations:
      "gui-x": "475"
      "gui-y": "800"
relations:
- - docker:docker
  - kubernetes-worker:container-runtime
- - docker:docker
  - kubernetes-control-plane:container-runtime
