# This is an incomplete bundle fragment. Do not attempt to deploy.
services:
  "docker":
    charm: cs:~containers/docker
    annotations:
      "gui-x": "475"
      "gui-y": "800"
relations:
- - docker:docker
  - kubernetes-worker:container-runtime
- - docker:docker
  - kubernetes-master:container-runtime
